WITH TEMP AS (
	SELECT
		*, 
		ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY CHANGE_DATE DESC) AS RN
	FROM 
		PRODUCTS
	WHERE 
		CHANGE_DATE <= '2019-08-16'
)

SELECT 
	P.PRODUCT_ID, 
	ISNULL(NEW_PRICE,10) AS PRICE 
FROM (
	SELECT 
		DISTINCT PRODUCT_ID
	FROM 
		PRODUCTS
	) AS P
LEFT JOIN 
	TEMP T
ON 
	P.PRODUCT_ID = T.PRODUCT_ID
WHERE 
	RN = 1 OR RN IS NULL