SELECT 
    QUERY_NAME, 
    ROUND(AVG(RATING * 1.0/POSITION),2) AS QUALITY,
    ROUND(SUM(CASE WHEN RATING<3 THEN 1.0 ELSE 0 END)/COUNT(RATING) * 100,2) AS poor_query_percentage
FROM QUERIES
GROUP BY QUERY_NAME
