WITH FILTERING AS (
	SELECT 
		*, DATEDIFF(DAY, order_date, customer_pref_delivery_date) AS DAYS_DIFF,
		(ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE)) AS RN
	FROM 
		Delivery
)

SELECT
	ROUND(
		SUM(CASE WHEN DAYS_DIFF = 0 THEN CAST(1 AS FLOAT) ELSE 0 END)
		/COUNT(DAYS_DIFF) * 100
	, 2) AS immediate_percentage
FROM FILTERING
WHERE RN = 1
