DECLARE @TOTAL_PLAYERS FLOAT;
SELECT @TOTAL_PLAYERS = COUNT(DISTINCT PLAYER_ID) FROM Activity;

WITH ROWADDED AS (
	SELECT 
		*,
		(ROW_NUMBER() OVER (PARTITION BY PLAYER_ID ORDER BY EVENT_DATE)) AS RN
	FROM
		ACTIVITY
)

SELECT 
	ROUND(
		COUNT(R1.PLAYER_ID)/@TOTAL_PLAYERS
	, 2) AS fraction 
FROM 
	ROWADDED R1
JOIN 
	ROWADDED R2
ON 
	R1.player_id = R2.player_id
	AND R1.RN = 1 AND R2.RN = 2
WHERE 
	DATEDIFF(DAY, R1.event_date, R2.event_date) = 1